services:
  - type: web
    name: laundry-api
    runtime: docker
    repo: https://github.com/dev-hmo/laundrypos
    branch: main
    rootDir: backend
    plan: free
    region: oregon
    healthCheckPath: /api/v1/health
    envVars:
      - key: DATABASE_URL
        value: postgres://app_user:app_user_pass_2024@dpg-d95qd9ojs32c7388a6o0-a.oregon-postgres.render.com/laundry_oms
      - key: CORS_ORIGINS
        value: https://laundry-oms-eight.vercel.app
      - key: AUTH_SECRET
        value: 91a252b90434fb899899b06eba04f9f38775b3f9596c5f4ce8be14e2468689a9
